<?php

return [
'action' => 'Tindakan',
              'admin_list' => 'Daftar Admin',
              'agent_list' => 'Daftar Agen',
              'cancelled' => 'Dibatalkan',
              'change' => 'Perubahan',
              'complete' => 'Lengkap',
              'conversion' => 'Konversi',
              'currencies' => 'Mata uang',
              'dashboard' => 'Dasbor',
              'datetime' => 'Tanggal Waktu',
              'description' => 'Deskripsi',
              'enter_amount' => 'Masukkan jumlah Anda',
              'first' => 'Pertama',
              'from_currency' => 'Mata Uang Dari',
              'index' => 'Tidak.',
              'info_empty' => 'Tidak ada catatan yang tersedia',
              'info_filtered' => '(difilter dari MAX total record)',
              'info_table' => 'Menampilkan halaman PAGE ke PAGES dari catatan MAX',
              'last' => 'Terakhir',
              'length_menu' => 'Tampilkan catatan MENU per halaman',
              'loading_records' => 'Memuat...',
              'new_order' => 'Pesanan baru',
              'next' => 'Lanjut',
              'not_setting_yet' => 'Belum diatur',
              'order_id' => 'Id pemesanan',
              'order_or_transaction_id' => 'ID Pesanan / ID Transaksi',
              'orders' => 'Pesanan',
              'pending_orders' => 'Pesanan Tertunda',
              'previous' => 'Sebelumnya',
              'print' => 'Mencetak',
              'processing..' => 'Pengolahan...',
              'profile' => 'Profil',
              'rate' => 'Menilai',
              'rates' => 'Tarif',
              'search' => 'Cari:',
              'set_rates' => 'Tetapkan Tarif',
              'status' => 'Status',
              'to_currency' => 'Mata uang untuk',
              'total' => 'Total',
              'upload_doc' => 'Unggah Dokumen',
              'user' => 'Pengguna',
              'user_list' => 'Daftar pengguna',
              'user_settings' => 'Pengaturan pengguna',
              'view_receipt' => 'Lihat Tanda Terima',
              'zero_records' => 'Tidak ada yang ditemukan'
              ]
?> 
